name: Build Android APK (Debug)
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - run: npm ci
      - run: npm run build
      - run: npx cap sync android
      - run: cd android && ./gradlew assembleDebug
      - name: Zip APK
        run: |
          cd android/app/build/outputs/apk/debug
          zip -r WishCraft-debug-${{ github.run_number }}.zip app-debug.apk
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WishCraft-APK-ZIP
          path: android/app/build/outputs/apk/debug/WishCraft-debug-*.zip
