name: Build Android APK (Debug)
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Generate icons (favicon + PWA)
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

          mkdir -p public/icons

          # Base 512 icon (purple circle + white W)
          convert -size 512x512 xc:none -fill "#8b5cf6" -draw "circle 256,256 256,10" \
                  -gravity center -pointsize 260 -fill white -font DejaVu-Sans \
                  -annotate 0 "W" public/icons/icon-512.png

          # Scaled 192
          convert public/icons/icon-512.png -resize 192x192 public/icons/icon-192.png

          # Maskable: full-bleed (same art; acceptable for simple shapes)
          cp public/icons/icon-512.png public/icons/maskable-512.png
          cp public/icons/icon-192.png public/icons/maskable-192.png

          # Favicon
          convert public/icons/icon-512.png -resize 64x64 public/favicon.ico

      # Use install instead of ci (no lockfile required)
      - name: Install deps
        run: npm install --no-audit --fund=false

      - name: Build web bundle
        run: npm run build

      # Generate android/ if it doesn't exist yet and sync
      - name: Add & sync Android platform
        run: |
          npx cap add android || true
          npx cap sync android
      - name: Capacitor native launcher icon (optional)
        run: |
          npm i -D @capacitor/assets
          # use the same generated art as source icon
          npx capacitor-assets generate --icon public/icons/icon-512.png --project android
   

      - name: Assemble debug APK
        run: cd android && ./gradlew assembleDebug

      - name: Zip APK
        run: |
          cd android/app/build/outputs/apk/debug
          zip -r WishCraft-debug-${{ github.run_number }}.zip app-debug.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WishCraft-APK-ZIP
          path: android/app/build/outputs/apk/debug/WishCraft-debug-*.zip
