name: Generate Android keystore
on:
  workflow_dispatch:
    inputs:
      alias:
        description: "Key alias"
        required: true
        default: wishcraft
      dname:
        description: 'Distinguished name (e.g. "CN=WishCraft,O=Joy Projects,C=IN")'
        required: true
        default: "CN=WishCraft,O=Joy Projects,C=IN"

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Generate a strong password
        id: pw
        shell: bash
        run: |
          STOREPASS="$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 24)"
          echo "storepass=$STOREPASS" >> "$GITHUB_OUTPUT"

      - name: Create keystore
        run: |
          keytool -genkeypair -v -keystore release.keystore \
            -alias "${{ github.event.inputs.alias }}" \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass "${{ steps.pw.outputs.storepass }}" \
            -keypass   "${{ steps.pw.outputs.storepass }}" \
            -dname "${{ github.event.inputs.dname }}"

      - name: Base64 encode (single line)
        run: |
          base64 -w 0 release.keystore > release.keystore.b64

      - name: Write metadata files
        run: |
          printf '%s' "${{ steps.pw.outputs.storepass }}" > keystore_password.txt
          printf '%s' "${{ github.event.inputs.alias }}" > key_alias.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-keystore
          path: |
            release.keystore
            release.keystore.b64
            keystore_password.txt
            key_alias.txt
